<a href="https://colab.research.google.com/github/zbo64876-coder/data-science-toolkit/blob/main/python_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 测试使用

## Python

1. Create a numpy array of size 2 x 2



In [ ]:
import numpy as np
array_2x2 = np.array([[1, 2], [3, 4]])
print(array_2x2)

[[1 2]
 [3 4]]


2. Create a random numpy array of size 3 x 4


In [ ]:
random_array_3x4 = np.random.rand(3, 4)
print(random_array_3x4)

[[0.54672335 0.14389866 0.16210246 0.80466997]
 [0.00952404 0.36152872 0.9509217  0.03451887]
 [0.67693599 0.37114966 0.6408202  0.98134897]]


3. Create a numpy array of ones and a numpy array of zeroes


In [ ]:
ones_array = np.ones((2, 3))
zeroes_array = np.zeros((3, 2))

print("Array of ones:")
print(ones_array)
print("\nArray of zeroes:")
print(zeroes_array)

Array of ones:
[[1. 1. 1.]
 [1. 1. 1.]]

Array of zeroes:
[[0. 0.]
 [0. 0.]
 [0. 0.]]


4. Create a random numpy array of size 6x3 and transpose it


In [ ]:
random_array_6x3 = np.random.rand(6, 3)
transposed_array = random_array_6x3.T

print("Original 6x3 array:")
print(random_array_6x3)
print("\nTransposed array:")
print(transposed_array)

Original 6x3 array:
[[0.83493114 0.13794665 0.40439291]
 [0.36782794 0.55322381 0.63422795]
 [0.99453359 0.75105215 0.55631895]
 [0.17135685 0.04285852 0.9529452 ]
 [0.68354688 0.0300591  0.15105293]
 [0.54078578 0.57982483 0.1098924 ]]

Transposed array:
[[0.83493114 0.36782794 0.99453359 0.17135685 0.68354688 0.54078578]
 [0.13794665 0.55322381 0.75105215 0.04285852 0.0300591  0.57982483]
 [0.40439291 0.63422795 0.55631895 0.9529452  0.15105293 0.1098924 ]]


5. Create two random numpy array of size n x p and p x m and then compute the dot product

In [ ]:
n, p, m = 3, 4, 2
array1 = np.random.rand(n, p)
array2 = np.random.rand(p, m)

dot_product = np.dot(array1, array2)

print("Array 1 (n x p):")
print(array1)
print("\nArray 2 (p x m):")
print(array2)
print("\nDot product (n x m):")
print(dot_product)

Array 1 (n x p):
[[0.98848344 0.75527956 0.18873086 0.07496129]
 [0.91332235 0.93540395 0.28905159 0.98303067]
 [0.52208503 0.25100724 0.94949067 0.70807289]]

Array 2 (p x m):
[[0.02141912 0.71032784]
 [0.16609169 0.24636293]
 [0.95449634 0.40019275]
 [0.23653759 0.29279752]]

Dot product (n x m):
[[0.34449218 0.98569739]
 [0.68334777 1.28271244]
 [1.12664404 1.01999168]]


## C++



```
# 此内容为代码格式
#include <bits/stdc++.h>
using namespace std;
int main(){
  cout<<"Hello, World!"<<endl;
  return 0;
}
```

